//
// Generated by LLVM NVPTX Back-End
//

.version 7.5
.target sm_20, texmode_independent
.address_size 64

	// .globl	test
.func  (.param .b64 func_retval0) _Z13get_global_idj
(
	.param .b32 _Z13get_global_idj_param_0
)
;

.entry test(
	.param .u64 .ptr .global .align 4 test_param_0,
	.param .u64 .ptr .global .align 4 test_param_1
)
{
	.reg .b32 	%r<2>;
	.reg .f32 	%f<4>;
	.reg .b64 	%rd<8>;

	ld.param.u64 	%rd2, [test_param_1];
	ld.param.u64 	%rd1, [test_param_0];
	mov.u32 	%r1, 0;
	{ // callseq 0, 0
	.reg .b32 temp_param_reg;
	.param .b32 param0;
	st.param.b32 	[param0+0], %r1;
	.param .b64 retval0;
	call.uni (retval0), 
	_Z13get_global_idj, 
	(
	param0
	);
	ld.param.b64 	%rd3, [retval0+0];
	} // callseq 0
	shl.b64 	%rd5, %rd3, 2;
	add.s64 	%rd6, %rd2, %rd5;
	ld.global.f32 	%f1, [%rd6];
	ld.global.f32 	%f2, [%rd6+4];
	add.rn.f32 	%f3, %f1, %f2;
	add.s64 	%rd7, %rd1, %rd5;
	st.global.f32 	[%rd7], %f3;
	ret;

}
